// Mirrors CONTENT.md. Change the copy there first, then here.
export const STRINGS = {
  clipButton: {
    label: "Clip",
  },
  panel: {
    heading: "Create clip",
    start: "Start",
    end: "End",
    useCurrentTime: "Use current time",
    useCurrentTimeForStart: "Use current time for start",
    useCurrentTimeForEnd: "Use current time for end",
    preview: "Preview",
    stopPreview: "Stop preview",
    errorUnreadableTime: "Enter a time like 1:23.",
    errorEndBeforeStart: "End must be after start.",
    errorOutsideVideo: "Time is outside the video.",
    close: "Close",
  },
  save: {
    button: "Save video",
    stop: "Stop saving",
    progress: (elapsed: string, length: string) => `Saving ${elapsed} / ${length}`,
    savingNote: "Let it play to the end. Pausing, skipping or closing this panel stops saving.",
    qualityNote:
      "Saves at the player's quality. For a steady result, pick one in Settings instead of Auto.",
    converting: (percent: number) => `Converting to MP4 ${percent}%`,
    convertingNote: "Converting to MP4. Closing this panel stops it.",
    saved: "Saved",
    announceStart: (length: string) => `Saving video. This takes ${length}.`,
    announceProgress: (elapsed: string, length: string) => `Saving ${elapsed} of ${length}`,
    announceConverting: "Converting to MP4",
    announceSaved: "Video saved",
    announceStopped: "Saving stopped",
    errors: {
      protected: "This video is protected and can't be saved.",
      ad: "An ad interrupted saving. Try again after it ends.",
      paused: "Saving stopped because the video was paused.",
      skipped: "Saving stopped because the video was skipped.",
      unsupported: "Your browser can't record this video.",
      failed: "Couldn't save the video.",
      webm: "Couldn't convert to MP4, so it was saved as WebM.",
    },
  },
  popup: {
    watchPageBody: "Clip a section of this video.",
    openPanel: "Open clip panel",
    closePanel: "Close clip panel",
    otherPage: "Open a YouTube video to clip it.",
    needsReload: "Reload this tab to use the extension.",
    reloadTab: "Reload tab",
  },
} as const;
